version: '3.8'
services:
  postgres:
    image: postgres:12.5
    ports:
    - 5433:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - ../.chainlink/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  evilthereum:
    image: evilthereum
    ports:
    - 8545:8545
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
    - ../.evilthereum/chaindb:/evilthereum/chaindb
    secrets:
    - api.txt
    - passphrase.txt
    environment:
    # NOTE: uncomment for debug
    # - NODE_ENV=debug
    - HTTP_PORT=8545
    - CHAIN_ID=${CHAIN_ID}
    - CHAIN_DB_PATH=${CHAIN_DB_PATH}
    - CHAINLINK_API_DSN=http://chainlink:6688
    - CHAINLINK_API_AUTH_FILE=/run/secrets/api.txt
    - CHAINLINK_DATABASE_DSN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    - CHAINLINK_VRF_KEY_PASSPHRASE_FILE=/run/secrets/passphrase.txt
  chainlink:
    image: smartcontract/chainlink:latest
    ports:
    - 6688:6688
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      evilthereum:
        condition: service_started
    command:
    - local
    - start
    - --api
    - /run/secrets/api.txt
    - --password
    - /run/secrets/passphrase.txt
    - --vrfpassword
    - /run/secrets/passphrase.txt
    volumes:
    - ../.chainlink/root:/chainlink
    secrets:
    - api.txt
    - passphrase.txt
    environment:
    - ROOT=/chainlink
    - LOG_LEVEL=debug
    - ETH_URL=ws://evilthereum:8545
    - ETH_CHAIN_ID=${CHAIN_ID}
    - ETH_GAS_PRICE_DEFAULT=0
    - GAS_UPDATER_ENABLED=false
    - MIN_INCOMING_CONFIRMATIONS=0
    - MIN_OUTGOING_CONFIRMATIONS=0
    - LINK_CONTRACT_ADDRESS=0x87cc55e4e3b0a7f8f34cee3a3b39c674b9501ef3
    - CHAINLINK_TLS_PORT=0
    - SECURE_COOKIES=false
    - ALLOW_ORIGINS=*
    - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    - DATABASE_TIMEOUT=0
secrets:
  api.txt:
    file: ../.chainlink/secret/api.txt
  passphrase.txt:
    file: ../.chainlink/secret/passphrase.txt
